language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository
jdk:
- oraclejdk8
branches:
  except:
  - gh-pages
script: ./gradlew check --stacktrace
notifications:
  slack:
    secure: Zx3N8RxVPnRwc7G7h+NnvQYE/LBLEmFAz73WIeWl128nURVUA+XyxqPA00QIxa4LBWXaS8iZjbdYpVKm6yALElYxnlkhkcwYhUmLAhUoUOoL58es7Eopj4xyeSjonwg8Hw2eJoMXPDK9w/VmM7/wajwYt73zaSBwrWWnzZVUU9ipnorUiCs9cVLuPswuNSgJ4sc1Ts4E568rDcmEC24iNPZA/oN2T5yFt4D8PfO++76wjhJeceRnKh0T/m2Khmt3xnC9CJGO+mKxzkqwrV6S/pCVdBHbaktjh6Cil9Rkv0GP0etBY9BLVBES5EzcnwS95on81tORtIaPqWNWxvY9tEDAHzOQj6LfeBdHUVP8Sr44Tr8i7Eu8TRXbHjWh7/wDy3WRul+4wm+DNn7pqRBE8ApQglwvsO9LoWiSdUjZS+qob/HrjZD6aEjYWktwluMpPe1R98f2w6DL/6iPv2EGwcqR7aYj5jXm1MvHREDLiLeZS/Tv0CSE8KwWMcol2d7zZpElnQQ4bC1tLbU+8r4vVcfA7/j+FccmdT3YmNIich5vNgJQrUnCOn1+D4HAwwtpY8oAVJpRFdBPX6hHGdhfjdMaL7FFwid6e+TnIly6l/I+N2CMiF0bPjp6wMTGyp0FeMy2dUipfV7XawFpq2Qnobp87KzJoFzll4mxYtt1MDw=
